FROM ubuntu:25.10

ARG USERNAME=ai
ARG USER_UID=1000
ARG USER_GID=1000
ARG GIT_USER
ARG GIT_EMAIL

# Rename the existing ubuntu user to ai (if it exists)
RUN if id ubuntu &>/dev/null; then \
        usermod -l ai ubuntu && \
        groupmod -n ai ubuntu && \
        usermod -d /home/ai -m ai; \
    else \
        useradd -m -s /bin/bash ai; \
    fi

# For OpenCode with Azure Cognitive Service
ENV AZURE_COGNITIVE_SERVICES_RESOURCE_NAME=aif-ai-sec

# General tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    curl \
    fish \
    git \
    gyp \
    gnupg \
    jq \
    less \
    nano \
    ripgrep \
    socat \
    tar \
    unzip \
    wget \
    file \
    strace \
    # Java
    maven \
    openjdk-21-jdk \
    # Node / JS
    nodejs \
    npm \
    # For AppImages
    libfuse2 \
    # for SDL (pygame)
    libsdl2-dev \
    libsdl2-image-dev \
    libsdl2-mixer-dev \ 
    libsdl2-ttf-dev \
    # OpenGL software
    libglvnd0 \
    libgl1 \
    libegl1 \ 
    libgles2 \ 
    libglvnd-dev \
    mesa-utils \
    libosmesa6 \
    libgl1-mesa-dri \
    # Headless screen
    xvfb \
    && rm -rf /var/lib/apt/lists/*

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Install gh cli
RUN mkdir -p -m 755 /etc/apt/keyrings \
	&& out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
	&& cat $out | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
	&& chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
	&& mkdir -p -m 755 /etc/apt/sources.list.d \
	&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
	&& apt-get update \
	&& apt-get install -y gh \
	&& rm -rf /var/lib/apt/lists/*

# Install GitLab CLI 
COPY --from=gitlab/glab:latest /usr/bin/glab /usr/local/bin/glab

# Install GO
RUN curl -OL https://golang.org/dl/go1.26.0.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.26.0.linux-amd64.tar.gz && \
    rm go1.26.0.linux-amd64.tar.gz

ENV GOPATH="/home/${USERNAME}/go"
ENV PATH="{$GOPATH}/bin:/usr/local/go/bin:${PATH}"

# Switch to non-root user    
USER ${USERNAME}
ENV HOME=/home/${USERNAME}
WORKDIR /home/${USERNAME}

# Make gopath folders as non-root
RUN mkdir -p $GOPATH/bin $GOPATH/src

# Install Python
RUN uv python install --default
ENV PATH="${HOME}/.local/bin:${PATH}"

# Pyhton tools
RUN uv tool install ruff@latest && \
    uv tool install ty@latest

# Love2d
RUN mkdir -p /home/ai/.local/bin \
    && curl -L "https://github.com/love2d/love/releases/download/11.5/love-11.5-x86_64.AppImage" -o /tmp/love.AppImage \
    && chmod +x /tmp/love.AppImage \
    && cd /home/ai/.local/bin \
    && /tmp/love.AppImage --appimage-extract \
    && mv squashfs-root love-11.5 \
    && rm /tmp/love.AppImage \
    && ln -s /home/ai/.local/bin/love-11.5/AppRun /home/ai/.local/bin/love

ENV SHELL=/bin/bash

# Set git user & email
RUN git config --global user.name "$GIT_USER" && \
    git config --global user.email "$GIT_NAME"

# Install Bun, OpenCode and Openchamber.
ENV BUN_INSTALL="$HOME/.bun"
ENV PATH="$BUN_INSTALL/bin:$PATH"
ENV npm_config_python="/usr/bin/python3"

RUN curl https://bun.sh/install | bash && \
    bun install -g opencode-ai && \
    npm install -g --prefix "$HOME/.local" @openchamber/web && \
    opencode --version && \
    openchamber --version


# # # Verify installed tools
RUN echo "Installed Versions" \
    && uv python list \
    && uv --version \
    # && dotnet --version \
    && java --version \
    && gh --version \
    && glab --version \
    && bun --version \
    && node --version \
    && npm --version \
    && openchamber --version \
    && opencode --version

# openchamber --port 8126 --ui-password 123
# codenomad --port 8127 --username vb --password 123
# nohup codenomad --host 0.0.0.0 --port 8127 --username vb --password 123 >> codenomad.log 2>&1 &
# CLI_API_TOKEN=a HAPI_API_URL=http://localhost:8128 HAPI_LISTEN_HOST=0.0.0.0 HAPI_LISTEN_PORT=8128 HAPI_PUBLIC_URL=http://localhost:8126 hapi hub 
# openchamber, codenomad, hapi codex, hapi opencode

RUN mkdir $HOME/ai-workdir

EXPOSE 8126
#ENTRYPOINT ["export NVM_DIR=\"$HOME/.nvm\" && [ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\" && openchamber --port 8126"]
#ENTRYPOINT ["bash", "-c", "source ~/.bashrc && openchamber --port 8126"]
ENTRYPOINT ["/bin/bash", "-c", "cd $HOME/ai-workdir && exec openchamber --port 8126"]
